name: "Hitch or Fist"
url: "http://matthewspencer.me/knots"
baseurl: "http://matthewspencer.me/knots"
# url: "http://localhost:4000"
permalink: "/:categories/:title/"
paginate: 12
paginate_path: "page/:num"
markdown: kramdown
exclude:
  - README.md