name: "Hitch or Fist"
url: "https://matthewspencer.github.io/knots/"
permalink: "/:categories/:title/"
paginate: 12
paginate_path: "page/:num"
markdown: kramdown
exclude:
  - README.md
  - bin
  - node_modules